# idiomes.py

translations = {
    "English": {
    "title": "🇨🇭 Swiss Finance Made Easy",
    "subtitle": "Hi, I'm Alex. I help you understand investments, health insurance, and taxes in Switzerland.",
    "about_me": "👋 About me",
    "what_i_help": "How I can help you",
    "topics": "📘 Financial Topics",
    "resources": "📂 Free Tools & Guides",
    "user": "📈 Personal Financial Projection",
    "book_call": "📅 Book a free call",
    "planner_title": "🌱 Your Future Planner",
    "personal_info": "👤 Personal Information & Lifestyle",
    "living_expenses": "🏠 Living Expenses",
    "life_goals": "🧭 Life Goals & Plans",
    "investment_preferences": "🎯 Investment Goals & Preferences",
    "projection_overview": "📊 Financial Projection Overview",
    "summary": "📝 Summary & Recommendations",
    "suggestions": "✅ Suggestions",
    "about_me_text": """
        My name is Alex, and I’m passionate about helping people confidently navigate the Swiss financial landscape. Whether you're a local or new to Switzerland, I simplify complex topics like retirement planning, health insurance, tax savings, and everyday budgeting.

        With years of experience working with expatriates and Swiss citizens, I offer personalized advice that works in real life, not just on paper.
    """,
    "what_i_help_text": """
        - Understand and optimize your Swiss 3rd pillar (Säule 3a)
        - Compare Krankenkasse models and save on health insurance
        - Budget effectively in high-cost cities
        - File taxes and maximize deductions
        - Financial planning for families, freelancers, and expatriates
        - Introduction to investing in ETFs in Switzerland
    """,
    "topic_1_title": "Swiss 3rd Pillar Explained (Säule 3a)",
    "topic_1_summary": "Discover how to reduce your taxes while saving for retirement. Learn the difference between bank and insurance options, and why not all 3a accounts are the same.",
    "topic_1_chart_caption": "Tax-advantaged growth over time",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "How Krankenkasse Really Works",
    "topic_2_summary": "Confused about Swiss health insurance? We break down basic and supplementary coverage, models like Telmed and HMO, and how to save over 1,000 CHF a year.",
    "topic_2_chart_caption": "Potential annual savings with model comparison",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Investing in Switzerland 101",
    "topic_3_summary": "Learn how to start investing with just 100 CHF/month. We’ll compare ETFs vs. savings, explain risk levels, and show you how to open your first Swiss brokerage account.",
    "topic_3_chart_caption": "Growth comparison: ETF vs. Savings",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Tax Deductions You’re Probably Missing",
    "topic_4_summary": "From 3a contributions to travel expenses, we make your tax return work for you. These tips can mean hundreds of francs back in your pocket.",
    "topic_4_chart_caption": "Chart of possible tax savings",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Monthly Budgeting in Switzerland",
    "topic_5_summary": "Living in Switzerland is expensive, but budgeting doesn’t have to be hard. Here’s a simple way to structure your monthly income using the 50/30/20 rule adapted to Swiss costs.",
    "topic_5_chart_caption": "Example of budget allocation",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "The True Cost of Living Alone in Switzerland",
    "topic_6_summary": "Thinking of moving out? We break down rent, insurance, transport, and food so you can realistically plan for living solo in Zurich, Geneva, or even Lugano.",
    "topic_6_chart_caption": "Estimated breakdown of costs to live alone",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Krankenkasse Change Deadline: What You Need to Know",
    "topic_7_summary": "Every November, you have the opportunity to save. This post explains the deadline, how to compare premiums, and send a cancellation letter.",
    "topic_7_chart_caption": "Savings from timely plan changes",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "Pillar 3a: Bank or Insurance?",
    "topic_8_summary": "Weighing your options? Learn why one offers more flexibility, while the other can lock you in for decades. Alex helps you decide what best suits your goals.",
    "topic_8_chart_caption": "Comparison of flexibility and performance",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Swiss Franc Stability and Investing",
    "topic_9_summary": "Why is the CHF considered ‘safe’? What does that mean for your long-term investment strategy? Understand the strength of the currency in simple terms.",
    "topic_9_chart_caption": "CHF vs. Other Global Currencies Comparison",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Expats: How to Navigate Swiss Finances",
    "topic_10_summary": "New to Switzerland? Here’s a quick guide on health insurance, mandatory coverage, and how to start saving or investing even as a newcomer.",
    "topic_10_chart_caption": "Financial integration roadmap for new residents",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
    "personal_info_expander": "👤 Personal & Lifestyle Information",
    "age": "🎂 Age",
    "relationship_status": "💍 Relationship Status",
    "relationship_status_options": ["Single", "Married", "Divorced", "Widowed"],
    "has_kids": "👶 Do you have children?",
    "has_kids_options": ["No", "Yes", "Planning to have"],
    "pets": "🐶 Pets",
    "pets_options": ["Dog", "Cat", "None", "Other"],
    "hobbies": "🎨 Hobbies",
    "hobbies_options": ["Travel", "Sports", "Reading", "Gaming", "Art", "Other"],
    "wants_to_travel": "✈️ Travel frequency",
    "wants_to_travel_options": ["Yes", "No", "Sometimes"],
    "career_field": "💼 Job Sector",
    "career_field_options": ["Tech", "Finance", "Healthcare", "Education", "Other"],
    "current_salary": "💵 Current Monthly Income (CHF)",

    "expenses_expander": "🏠 Living Expenses",
    "rent": "🏡 Monthly Rent / Mortgage",
    "food": "🍽️ Food & Groceries",
    "transport": "🚗 Transport",
    "entertainment": "🎭 Entertainment & Hobbies",
    "healthcare": "🩺 Healthcare & Insurance",
    "misc": "🧾 Other Expenses",
    "total_expenses_label": "💸 Total Monthly Living Cost",
    "preferences_note": "💭 _These preferences help personalize your financial roadmap more deeply._",

    "goals_expander": "🧭 Life Goals & Future Plans",
    "wants_children": "👶 Planning to have (more) children?",
    "wants_children_options": ["No", "Yes", "Maybe"],
    "dream_trip": "✈️ Dream travel destination or trip?",
    "travel_budget": "💸 Annual Travel Budget (CHF)",
    "major_purchase": "🚗 Next big purchase you're planning?",
    "major_purchase_options": ["Home", "Car", "Education", "Startup", "None"],
    "career_goal": "💼 Career ambitions or job changes in the next 5–10 years?",
    "lifestyle_upgrades": "🌟 Desired lifestyle upgrades",
    "lifestyle_upgrades_options": ["Luxury Living", "Work Flexibility", "More Leisure Time", "Move Abroad", "None"],
    "wellness_goals": "🧘‍♀️ Focus on wellness or mental health?",
    "wellness_goals_options": ["Yes", "No", "Trying to prioritize"],

    "investment_expander": "🎯 Goals & Investment Preferences",
    "wants_to_buy_house": "🏠 Planning to buy a house?",
    "wants_to_buy_house_options": ["Yes", "No", "Maybe"],
    "retirement_age": "🎉 Desired Retirement Age",
    "owns_home": "🏘️ Owns home now?",
    "owns_home_options": ["Yes", "No"],
    "has_3a": "💼 Has 3rd Pillar?",
    "has_3a_options": ["Yes", "No"],
    "has_etfs": "📈 Invests in ETFs/Index Funds?",
    "has_etfs_options": ["Yes", "No"],
    "other_assets": "💰 Other Assets",
    "other_assets_options": ["Real Estate", "Crypto", "Business", "High-yield Savings", "None"],
    "wants_to_invest_more": "➕ Increase Investment?",
    "wants_to_invest_more_options": ["Yes", "No", "Maybe"],
    "initial_savings": "💰 Current Savings & Investments (CHF)"
},
"projection_overview": "📊 Financial Projection Overview",
"income_vs_expenses_chart": "💵 Income vs Expenses",
"summary_recommendations": "📝 Summary & Recommendations",
"suggestions": "✅ Suggestions"

},
   "German": {
    "title": "🇨🇭 Finanzplanung einfach gemacht",
    "subtitle": "Hallo, ich bin Alex. Ich helfe dir, Investitionen, Krankenversicherung und Steuern in der Schweiz zu verstehen.",
    "about_me": "👋 Über mich",
    "what_i_help": "Wie ich dir helfen kann",
    "topics": "📘 Finanzthemen",
    "resources": "📂 Kostenlose Tools & Leitfäden",
    "user": "📈 Persönliche Finanzprojektion",
    "book_call": "📅 Buche ein kostenloses Gespräch",
    "planner_title": "🌱 Dein Zukunftsplaner",
    "personal_info": "👤 Persönliche Informationen & Lebensstil",
    "living_expenses": "🏠 Lebenshaltungskosten",
    "life_goals": "🧭 Lebensziele & Pläne",
    "investment_preferences": "🎯 Investitionsziele & Präferenzen",
    "projection_overview": "📊 Finanzprognose Übersicht",
    "summary": "📝 Zusammenfassung & Empfehlungen",
    "suggestions": "✅ Vorschläge",
    "about_me_text": """
        Mein Name ist Alex und ich bin leidenschaftlich daran interessiert, Menschen zu helfen, sich sicher im schweizerischen Finanzumfeld zurechtzufinden. Egal, ob du Einheimischer oder neu in der Schweiz bist, ich vereinfache komplexe Themen wie Altersvorsorge, Krankenversicherung, Steuervorteile und alltägliches Budgetieren.

        Mit jahrelanger Erfahrung in der Zusammenarbeit mit Expats und Schweizer Bürgern biete ich maßgeschneiderte Beratung, die im realen Leben funktioniert, nicht nur auf dem Papier.
    """,
    "what_i_help_text": """
        - Verstehe und optimiere deine Säule 3a (3. Säule)
        - Vergleiche Krankenkassenmodelle und spare bei der Krankenversicherung
        - Effektives Budgetieren in teuren Städten
        - Steuererklärung und Maximierung von Abzügen
        - Finanzplanung für Familien, Freiberufler und Expats
        - Einführung in die Investition in ETFs in der Schweiz
    """,
    "topic_1_title": "Schweizer Säule 3a erklärt",
    "topic_1_summary": "Entdecke, wie du deine Steuern senken und für den Ruhestand sparen kannst. Lerne den Unterschied zwischen Bank- und Versicherungsoptionen und warum nicht alle 3a-Konten gleich sind.",
    "topic_1_chart_caption": "Steuervorteile über die Zeit",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "Wie die Krankenkasse wirklich funktioniert",
    "topic_2_summary": "Verwirrt von der Schweizer Krankenversicherung? Wir erklären die Grund- und Zusatzversicherungen, Modelle wie Telmed und HMO und wie du über 1.000 CHF pro Jahr sparen kannst.",
    "topic_2_chart_caption": "Mögliche jährliche Einsparungen mit Modellvergleich",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Investieren in der Schweiz 101",
    "topic_3_summary": "Lerne, wie du mit nur 100 CHF/Monat investieren kannst. Wir vergleichen ETFs vs. Sparkonten, erklären Risikostufen und zeigen dir, wie du dein erstes Schweizer Brokerkonto eröffnest.",
    "topic_3_chart_caption": "Vergleich des Wachstums: ETF vs. Sparkonto",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Steuerabzüge, die du wahrscheinlich verpasst",
    "topic_4_summary": "Von 3a-Beiträgen bis hin zu Reisekosten – wir machen deine Steuererklärung für dich. Diese Tipps können Hunderte von Franken zurück in deine Tasche bringen.",
    "topic_4_chart_caption": "Diagramm möglicher Steuerersparnisse",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Monatliches Budgetieren in der Schweiz",
    "topic_5_summary": "Das Leben in der Schweiz ist teuer, aber Budgetieren muss nicht schwer sein. Hier ist eine einfache Möglichkeit, dein monatliches Einkommen mit der 50/30/20-Regel an die Schweizer Kosten anzupassen.",
    "topic_5_chart_caption": "Beispiel für Budgetaufteilung",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "Die wahren Kosten des Alleinlebens in der Schweiz",
    "topic_6_summary": "Denkst du darüber nach, auszuziehen? Wir erklären Miete, Versicherung, Transport und Essen, damit du realistisch für das Leben allein in Zürich, Genf oder Lugano planen kannst.",
    "topic_6_chart_caption": "Geschätzte Aufschlüsselung der Lebenshaltungskosten für Alleinlebende",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Krankenkassenwechsel: Was du wissen musst",
    "topic_7_summary": "Jeden November hast du die Möglichkeit, zu sparen. In diesem Beitrag erklären wir den Stichtag, wie du Prämien vergleichst und ein Kündigungsschreiben sendest.",
    "topic_7_chart_caption": "Einsparungen durch rechtzeitige Planänderungen",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "Säule 3a: Bank oder Versicherung?",
    "topic_8_summary": "Bist du unschlüssig? Lerne, warum eine mehr Flexibilität bietet, während die andere dich für Jahrzehnten binden kann. Alex hilft dir zu entscheiden, was am besten zu deinen Zielen passt.",
    "topic_8_chart_caption": "Vergleich der Flexibilität und Leistung",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Stabilität des Schweizer Franken und Investieren",
    "topic_9_summary": "Warum wird der CHF als ‚sicher‘ angesehen? Was bedeutet das für deine langfristige Anlagestrategie? Verstehe die Stärke der Währung in einfachen Worten.",
    "topic_9_chart_caption": "Vergleich CHF vs. Andere globale Währungen",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Expats: Wie man sich im Schweizer Finanzsystem zurechtfindet",
    "topic_10_summary": "Neu in der Schweiz? Hier ist ein kurzer Leitfaden zu Krankenversicherung, obligatorischer Deckung und wie du auch als Neuling mit dem Sparen oder Investieren beginnen kannst.",
    "topic_10_chart_caption": "Finanzielle Integrations-Roadmap für neue Bewohner",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
      "personal_info_expander": "👤 Persönliche & Lebensstil-Informationen",
      "age": "🎂 Alter",
      "relationship_status": "💍 Beziehungsstatus",
      "relationship_status_options": ["Ledig", "Verheiratet", "Geschieden", "Witwe/Witwer"],
      "has_kids": "👶 Hast du Kinder?",
      "has_kids_options": ["Nein", "Ja", "Planen, welche zu haben"],
      "pets": "🐶 Haustiere",
      "pets_options": ["Hund", "Katze", "Keins", "Andere"],
      "hobbies": "🎨 Hobbys",
      "hobbies_options": ["Reisen", "Sport", "Lesen", "Gaming", "Kunst", "Andere"],
      "wants_to_travel": "✈️ Häufigkeit des Reisens",
      "wants_to_travel_options": ["Ja", "Nein", "Manchmal"],
      "career_field": "💼 Berufsfeld",
      "career_field_options": ["Technologie", "Finanzen", "Gesundheitswesen", "Bildung", "Andere"],
      "current_salary": "💵 Aktuelles Monatseinkommen (CHF)",
      "expenses_expander": "🏠 Lebenshaltungskosten",
      "rent": "🏡 Monatliche Miete / Hypothek",
      "food": "🍽️ Lebensmittel & Einkäufe",
      "transport": "🚗 Transport",
      "entertainment": "🎭 Unterhaltung & Hobbys",
      "healthcare": "🩺 Gesundheitswesen & Versicherung",
      "misc": "🧾 Sonstige Ausgaben",
      "total_expenses_label": "💸 Gesamte monatliche Lebenshaltungskosten",
      "preferences_note": "💭 _Diese Präferenzen helfen, deinen finanziellen Fahrplan tiefer zu personalisieren._",
      "goals_expander": "🧭 Lebensziele & Zukunftspläne",
      "wants_children": "👶 Planst du (mehr) Kinder?",
      "wants_children_options": ["Nein", "Ja", "Vielleicht"],
      "dream_trip": "✈️ Traumreiseziel oder -trip?",
      "travel_budget": "💸 Jährliches Reisebudget (CHF)",
      "major_purchase": "🚗 Große Anschaffung, die du planst?",
      "major_purchase_options": ["Haus", "Auto", "Ausbildung", "Start-up", "Keine"],
      "career_goal": "💼 Karriereziele oder Berufswechsel in den nächsten 5-10 Jahren?",
      "lifestyle_upgrades": "🌟 Gewünschte Lebensstil-Upgrades",
      "lifestyle_upgrades_options": ["Luxuswohnen", "Arbeitsflexibilität", "Mehr Freizeit", "Ins Ausland ziehen", "Keine"],
      "wellness_goals": "🧘‍♀️ Fokus auf Wellness oder mentale Gesundheit?",
      "wellness_goals_options": ["Ja", "Nein", "Versuche es zu priorisieren"],
      "investment_expander": "🎯 Ziele & Investitionspräferenzen",
      "wants_to_buy_house": "🏠 Planst du ein Haus zu kaufen?",
      "wants_to_buy_house_options": ["Ja", "Nein", "Vielleicht"],
      "retirement_age": "🎉 Gewünschtes Rentenalter",
      "owns_home": "🏘️ Eigentum?",
      "owns_home_options": ["Ja", "Nein"],
      "has_3a": "💼 Hat Säule 3a?",
      "has_3a_options": ["Ja", "Nein"],
      "has_etfs": "📈 Investierst du in ETFs/Indexfonds?",
      "has_etfs_options": ["Ja", "Nein"],
      "other_assets": "💰 Andere Vermögenswerte",
      "other_assets_options": ["Immobilien", "Krypto", "Unternehmen", "Hochverzinsliche Sparkonten", "Keine"],
      "wants_to_invest_more": "➕ Möchtest du mehr investieren?",
      "wants_to_invest_more_options": ["Ja", "Nein", "Vielleicht"],
      "initial_savings": "💰 Aktuelle Ersparnisse & Investitionen (CHF)"
    },
    "projection_overview": "📊 Finanzprognose Übersicht",
    "income_vs_expenses_chart": "💵 Einkommen vs Ausgaben",
    "summary_recommendations": "📝 Zusammenfassung & Empfehlungen",
    "suggestions": "✅ Vorschläge"
},
    "Français": {
    "title": "🇨🇭 Finances Suisses Simplifiées",
    "subtitle": "Salut, je suis Alex. Je vous aide à comprendre les investissements, l'assurance santé et les impôts en Suisse.",
    "about_me": "👋 À propos de moi",
    "what_i_help": "Comment je peux vous aider",
    "topics": "📘 Thèmes financiers",
    "resources": "📂 Outils et guides gratuits",
    "user": "📈 Projection financière personnelle",
    "book_call": "📅 Réservez un appel gratuit",
    "planner_title": "🌱 Votre Planificateur de l'Avenir",
    "personal_info": "👤 Informations personnelles & Mode de vie",
    "living_expenses": "🏠 Dépenses de vie",
    "life_goals": "🧭 Objectifs de vie & Projets",
    "investment_preferences": "🎯 Objectifs d'investissement & Préférences",
    "projection_overview": "📊 Aperçu de la projection financière",
    "summary": "📝 Résumé & Recommandations",
    "suggestions": "✅ Suggestions",
    "about_me_text": """
        Je m'appelle Alex et je suis passionné par l'aide aux personnes pour naviguer en toute confiance dans le paysage financier suisse. Que vous soyez local ou nouvel arrivant en Suisse, je simplifie des sujets complexes comme la planification de la retraite, l'assurance santé, les économies fiscales et la gestion du budget quotidien.

        Fort de plusieurs années d'expérience avec les expatriés et les citoyens suisses, je propose des conseils personnalisés qui fonctionnent dans la vie réelle, pas seulement sur le papier.
    """,
    "what_i_help_text": """
        - Comprendre et optimiser votre pilier 3a (Säule 3a)
        - Comparer les modèles de Krankenkasse et économiser sur l'assurance santé
        - Établir un budget efficace dans des villes coûteuses
        - Déclarer vos impôts et maximiser vos déductions
        - Planification financière pour les familles, freelances et expatriés
        - Introduction à l'investissement dans des ETF en Suisse
    """,
    "topic_1_title": "Pilier 3a expliqué (Säule 3a)",
    "topic_1_summary": "Découvrez comment réduire vos impôts tout en économisant pour la retraite. Apprenez la différence entre les options bancaires et d'assurance et pourquoi tous les comptes 3a ne se valent pas.",
    "topic_1_chart_caption": "Croissance avantageuse fiscalement au fil du temps",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "Comment fonctionne réellement la Krankenkasse",
    "topic_2_summary": "Vous êtes perdu avec l'assurance santé en Suisse ? Nous décomposons la couverture de base et complémentaire, les modèles comme Telmed et HMO, et comment économiser plus de 1 000 CHF par an.",
    "topic_2_chart_caption": "Économies annuelles potentielles grâce à la comparaison des modèles",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Investir en Suisse 101",
    "topic_3_summary": "Apprenez à investir avec seulement 100 CHF par mois. Nous comparerons les ETF vs les comptes d'épargne, expliquerons les niveaux de risque, et vous montrerons comment ouvrir votre premier compte de courtage suisse.",
    "topic_3_chart_caption": "Comparaison de la croissance : ETF vs Épargne",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Les déductions fiscales que vous manquez probablement",
    "topic_4_summary": "Des contributions 3a aux frais de voyage, nous faisons en sorte que votre déclaration d'impôts travaille pour vous. Ces astuces peuvent vous rapporter des centaines de francs.",
    "topic_4_chart_caption": "Graphique des économies fiscales possibles",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Budget mensuel en Suisse",
    "topic_5_summary": "Vivre en Suisse est coûteux, mais établir un budget ne doit pas être compliqué. Voici une méthode simple pour structurer vos revenus mensuels avec la règle 50/30/20 adaptée aux coûts suisses.",
    "topic_5_chart_caption": "Exemple d'allocation du budget",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "Le vrai coût de vivre seul en Suisse",
    "topic_6_summary": "Vous envisagez de partir vivre seul ? Nous détaillons le loyer, l'assurance, les transports et la nourriture pour que vous puissiez planifier concrètement votre vie en solo à Zurich, Genève ou Lugano.",
    "topic_6_chart_caption": "Répartition estimée des coûts pour vivre seul",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Date limite de changement de Krankenkasse : Ce que vous devez savoir",
    "topic_7_summary": "Chaque novembre, vous avez l'opportunité de réaliser des économies. Cet article explique la date limite, comment comparer les primes, et comment envoyer une lettre de résiliation.",
    "topic_7_chart_caption": "Économies réalisées grâce à des changements de plan en temps utile",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "Pilier 3a : Banque ou Assurance ?",
    "topic_8_summary": "Hésitez-vous ? Découvrez pourquoi l'une offre plus de flexibilité, tandis que l'autre peut vous enfermer pendant des décennies. Alex vous aide à choisir la solution la mieux adaptée à vos objectifs.",
    "topic_8_chart_caption": "Comparaison de la flexibilité et des performances",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Stabilité du franc suisse et investissements",
    "topic_9_summary": "Pourquoi le CHF est-il considéré comme « sûr » ? Que signifie cela pour votre stratégie d'investissement à long terme ? Comprenez la force de la devise en termes simples.",
    "topic_9_chart_caption": "Comparaison CHF vs Autres devises mondiales",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Expatriés : Comment naviguer dans les finances suisses",
    "topic_10_summary": "Nouveau en Suisse ? Voici un guide rapide sur l'assurance santé, la couverture obligatoire, et comment commencer à économiser ou investir même en tant que nouvel arrivant.",
    "topic_10_chart_caption": "Feuille de route d'intégration financière pour les nouveaux résidents",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
      "personal_info_expander": "👤 Informations personnelles & Mode de vie",
      "age": "🎂 Âge",
      "relationship_status": "💍 Statut marital",
      "relationship_status_options": ["Célibataire", "Marié", "Divorcé", "Veuf/Veuve"],
      "has_kids": "👶 Avez-vous des enfants ?",
      "has_kids_options": ["Non", "Oui", "Planifiez d'en avoir"],
      "pets": "🐶 Animaux de compagnie",
      "pets_options": ["Chien", "Chat", "Aucun", "Autre"],
      "hobbies": "🎨 Loisirs",
      "hobbies_options": ["Voyager", "Sports", "Lecture", "Jeux vidéo", "Art", "Autre"],
      "wants_to_travel": "✈️ Fréquence des voyages",
      "wants_to_travel_options": ["Oui", "Non", "Parfois"],
      "career_field": "💼 Secteur d'activité",
      "career_field_options": ["Technologie", "Finance", "Santé", "Éducation", "Autre"],
      "current_salary": "💵 Salaire mensuel actuel (CHF)",
      "expenses_expander": "🏠 Dépenses de vie",
      "rent": "🏡 Loyer / Hypothèque mensuel",
      "food": "🍽️ Nourriture & Courses",
      "transport": "🚗 Transport",
      "entertainment": "🎭 Divertissement & Loisirs",
      "healthcare": "🩺 Soins de santé & Assurance",
      "misc": "🧾 Autres dépenses",
      "total_expenses_label": "💸 Coût total mensuel de la vie",
      "preferences_note": "💭 _Ces préférences aident à personnaliser davantage votre plan financier._",
      "goals_expander": "🧭 Objectifs de vie & Plans futurs",
      "wants_children": "👶 Envisagez-vous d'avoir (plus) d'enfants ?",
      "wants_children_options": ["Non", "Oui", "Peut-être"],
      "dream_trip": "✈️ Destination ou voyage de rêve ?",
      "travel_budget": "💸 Budget annuel pour les voyages (CHF)",
      "major_purchase": "🚗 Grande acquisition prévue ?",
      "major_purchase_options": ["Maison", "Voiture", "Éducation", "Start-up", "Aucune"],
      "career_goal": "💼 Ambitions professionnelles ou changements de travail dans les 5 à 10 prochaines années ?",
      "lifestyle_upgrades": "🌟 Améliorations du style de vie souhaitées",
      "lifestyle_upgrades_options": ["Vie de luxe", "Flexibilité du travail", "Plus de temps libre", "Déménager à l'étranger", "Aucune"],
      "wellness_goals": "🧘‍♀️ Focus sur le bien-être ou la santé mentale ?",
      "wellness_goals_options": ["Oui", "Non", "Essaye de prioriser"],
      "investment_expander": "🎯 Objectifs & Préférences d'investissement",
      "wants_to_buy_house": "🏠 Envisagez-vous d'acheter une maison ?",
      "wants_to_buy_house_options": ["Oui", "Non", "Peut-être"],
      "retirement_age": "🎉 Âge de retraite souhaité",
      "owns_home": "🏘️ Propriétaire de votre maison ?",
      "owns_home_options": ["Oui", "Non"],
      "has_3a": "💼 Avez-vous un Pilier 3a ?",
      "has_3a_options": ["Oui", "Non"],
      "has_etfs": "📈 Investissez-vous dans des ETFs/Fonds indiciels ?",
      "has_etfs_options": ["Oui", "Non"],
      "other_assets": "💰 Autres actifs",
      "other_assets_options": ["Immobilier", "Cryptomonnaies", "Entreprise", "Comptes d'épargne à haut rendement", "Aucun"],
      "wants_to_invest_more": "➕ Souhaitez-vous investir davantage ?",
      "wants_to_invest_more_options": ["Oui", "Non", "Peut-être"],
      "initial_savings": "💰 Économies & investissements actuels (CHF)"
    },
    "projection_overview": "📊 Aperçu de la projection financière",
    "income_vs_expenses_chart": "💵 Revenus vs Dépenses",
    "summary_recommendations": "📝 Résumé & Recommandations",
    "suggestions": "✅ Suggestions"

},
    "Italiano": {
    "title": "🇨🇭 Finanza Svizzera Semplificata",
    "subtitle": "Ciao, sono Alex. Ti aiuto a capire gli investimenti, l'assicurazione sanitaria e le tasse in Svizzera.",
    "about_me": "👋 Chi sono",
    "what_i_help": "Come posso aiutarti",
    "topics": "📘 Argomenti Finanziari",
    "resources": "📂 Strumenti e Guide Gratuite",
    "user": "📈 Proiezione Finanziaria Personale",
    "book_call": "📅 Prenota una chiamata gratuita",
    "planner_title": "🌱 Il Tuo Pianificatore del Futuro",
    "personal_info": "👤 Informazioni Personali & Stile di Vita",
    "living_expenses": "🏠 Spese di Vita",
    "life_goals": "🧭 Obiettivi di Vita & Piani Futuroidi",
    "investment_preferences": "🎯 Obiettivi di Investimento & Preferenze",
    "projection_overview": "📊 Panoramica della Proiezione Finanziaria",
    "summary": "📝 Riepilogo & Raccomandazioni",
    "suggestions": "✅ Suggerimenti",
    "about_me_text": """
        Mi chiamo Alex e sono appassionato nell'aiutare le persone a navigare con fiducia nel panorama finanziario svizzero. Che tu sia un residente o un nuovo arrivato in Svizzera, semplifico argomenti complessi come la pianificazione della pensione, l'assicurazione sanitaria, le tasse e il bilancio quotidiano.

        Con anni di esperienza nell'aiutare expatriati e cittadini svizzeri, offro consulenze personalizzate che funzionano nella vita reale, non solo sulla carta.
    """,
    "what_i_help_text": """
        - Comprendere e ottimizzare il tuo 3° pilastro (Säule 3a)
        - Confrontare i modelli di Krankenkasse e risparmiare sull'assicurazione sanitaria
        - Creare un bilancio efficace nelle città ad alto costo
        - Dichiarare le tasse e massimizzare le detrazioni
        - Pianificazione finanziaria per famiglie, freelance ed expatriati
        - Introduzione all'investimento in ETF in Svizzera
    """,
    "topic_1_title": "3° Pilastro spiegato (Säule 3a)",
    "topic_1_summary": "Scopri come ridurre le tasse mentre risparmi per la pensione. Impara la differenza tra le opzioni bancarie e assicurative e perché non tutti i conti 3a sono uguali.",
    "topic_1_chart_caption": "Crescita fiscale vantaggiosa nel tempo",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "Come funziona davvero Krankenkasse",
    "topic_2_summary": "Confuso sull'assicurazione sanitaria in Svizzera? Spieghiamo la copertura di base e supplementare, i modelli come Telmed e HMO e come risparmiare oltre 1.000 CHF all'anno.",
    "topic_2_chart_caption": "Potenziale risparmio annuale con il confronto dei modelli",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Investire in Svizzera 101",
    "topic_3_summary": "Impara come iniziare a investire con solo 100 CHF al mese. Confronteremo ETF vs risparmio, spiegheremo i livelli di rischio e ti mostreremo come aprire il tuo primo conto di intermediazione svizzero.",
    "topic_3_chart_caption": "Confronto di crescita: ETF vs Risparmio",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Detrazioni fiscali che probabilmente stai perdendo",
    "topic_4_summary": "Dalle contribuzioni al 3a alle spese di viaggio, facciamo in modo che la tua dichiarazione fiscale lavori per te. Questi consigli possono farti guadagnare centinaia di franchi.",
    "topic_4_chart_caption": "Grafico delle potenziali risparmi fiscali",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Pianificazione del Budget Mensile in Svizzera",
    "topic_5_summary": "Vivere in Svizzera è costoso, ma il budgeting non deve essere difficile. Ecco un modo semplice per strutturare il tuo reddito mensile utilizzando la regola 50/30/20 adattata ai costi svizzeri.",
    "topic_5_chart_caption": "Esempio di allocazione del budget",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "Il vero costo di vivere da soli in Svizzera",
    "topic_6_summary": "Stai pensando di vivere da solo? Spieghiamo l'affitto, l'assicurazione, i trasporti e il cibo in modo che tu possa pianificare realisticamente la vita da solo a Zurigo, Ginevra o Lugano.",
    "topic_6_chart_caption": "Ripartizione stimata dei costi per vivere da solo",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Scadenza per il cambiamento della Krankenkasse: Cosa devi sapere",
    "topic_7_summary": "Ogni novembre hai l'opportunità di risparmiare. Questo articolo spiega la scadenza, come confrontare i premi e inviare una lettera di disdetta.",
    "topic_7_chart_caption": "Risparmio grazie ai cambiamenti tempestivi del piano",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "3a: Banca o Assicurazione?",
    "topic_8_summary": "Sei indeciso? Scopri perché una offre più flessibilità mentre l'altra ti lega per decenni. Alex ti aiuta a decidere cosa è meglio per i tuoi obiettivi.",
    "topic_8_chart_caption": "Confronto di flessibilità e performance",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Stabilità del Franco Svizzero e Investimenti",
    "topic_9_summary": "Perché il CHF è considerato 'sicuro'? Cosa significa per la tua strategia d'investimento a lungo termine? Comprendi la forza della valuta in termini semplici.",
    "topic_9_chart_caption": "Confronto del CHF con altre valute globali",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Espatriati: Come orientarsi nelle finanze svizzere",
    "topic_10_summary": "Nuovo in Svizzera? Ecco una guida rapida sull'assicurazione sanitaria, la copertura obbligatoria e su come iniziare a risparmiare o investire anche da nuovo arrivato.",
    "topic_10_chart_caption": "Mappa di integrazione finanziaria per nuovi residenti",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
      "personal_info_expander": "👤 Informazioni personali & Stile di vita",
      "age": "🎂 Età",
      "relationship_status": "💍 Stato civile",
      "relationship_status_options": ["Celibe", "Sposato", "Divorziato", "Vedovo"],
      "has_kids": "👶 Hai figli?",
      "has_kids_options": ["No", "Sì", "In programma di averne"],
      "pets": "🐶 Animali domestici",
      "pets_options": ["Cane", "Gatto", "Nessuno", "Altro"],
      "hobbies": "🎨 Passatempi",
      "hobbies_options": ["Viaggiare", "Sport", "Lettura", "Videogiochi", "Arte", "Altro"],
      "wants_to_travel": "✈️ Frequenza dei viaggi",
      "wants_to_travel_options": ["Sì", "No", "A volte"],
      "career_field": "💼 Settore lavorativo",
      "career_field_options": ["Tecnologia", "Finanza", "Sanità", "Educazione", "Altro"],
      "current_salary": "💵 Reddito mensile attuale (CHF)",
      "expenses_expander": "🏠 Spese di vita",
      "rent": "🏡 Affitto / Mutuo mensile",
      "food": "🍽️ Cibo & Generi alimentari",
      "transport": "🚗 Trasporti",
      "entertainment": "🎭 Divertimenti & Passatempi",
      "healthcare": "🩺 Assicurazione sanitaria & Spese sanitarie",
      "misc": "🧾 Altre spese",
      "total_expenses_label": "💸 Costo totale mensile della vita",
      "preferences_note": "💭 _Queste preferenze aiutano a personalizzare ulteriormente la tua roadmap finanziaria._",
      "goals_expander": "🧭 Obiettivi di vita & Piani futuri",
      "wants_children": "👶 Prevedi di avere (altri) figli?",
      "wants_children_options": ["No", "Sì", "Forse"],
      "dream_trip": "✈️ Destinazione o viaggio dei sogni?",
      "travel_budget": "💸 Budget annuale per i viaggi (CHF)",
      "major_purchase": "🚗 Prossimo grande acquisto previsto?",
      "major_purchase_options": ["Casa", "Auto", "Educazione", "Startup", "Nessuno"],
      "career_goal": "💼 Ambizioni professionali o cambiamenti di lavoro nei prossimi 5-10 anni?",
      "lifestyle_upgrades": "🌟 Miglioramenti desiderati nel tuo stile di vita",
      "lifestyle_upgrades_options": ["Vivere in lusso", "Flessibilità lavorativa", "Più tempo libero", "Trasferirsi all'estero", "Nessuno"],
      "wellness_goals": "🧘‍♀️ Obiettivi legati al benessere o alla salute mentale?",
      "wellness_goals_options": ["Sì", "No", "Sto cercando di dare priorità"],
      "investment_expander": "🎯 Obiettivi & Preferenze di investimento",
      "wants_to_buy_house": "🏠 Prevedi di comprare una casa?",
      "wants_to_buy_house_options": ["Sì", "No", "Forse"],
      "retirement_age": "🎉 Età di pensionamento desiderata",
      "owns_home": "🏘️ Possiedi già una casa?",
      "owns_home_options": ["Sì", "No"],
      "has_3a": "💼 Hai un Pilastro 3a?",
      "has_3a_options": ["Sì", "No"],
      "has_etfs": "📈 Investi in ETF/Fondi indicizzati?",
      "has_etfs_options": ["Sì", "No"],
      "other_assets": "💰 Altri asset",
      "other_assets_options": ["Immobiliare", "Criptovalute", "Business", "Conti risparmio ad alto rendimento", "Nessuno"],
      "wants_to_invest_more": "➕ Vuoi investire di più?",
      "wants_to_invest_more_options": ["Sì", "No", "Forse"],
      "initial_savings": "💰 Risparmi e investimenti attuali (CHF)"
    },
    "projection_overview": "📊 Panoramica della proiezione finanziaria",
    "income_vs_expenses_chart": "💵 Reddito vs Spese",
    "summary_recommendations": "📝 Riepilogo e raccomandazioni",
    "suggestions": "✅ Suggerimenti"
},
    "Español": {
    "title": "🇨🇭 Finanzas Suizas Hechas Fácil",
    "subtitle": "Hola, soy Alex. Te ayudo a entender las inversiones, el seguro de salud y los impuestos en Suiza.",
    "about_me": "👋 Acerca de mí",
    "what_i_help": "Cómo puedo ayudarte",
    "topics": "📘 Temas Financieros",
    "resources": "📂 Herramientas y Guías Gratis",
    "user": "📈 Proyección Financiera Personal",
    "book_call": "📅 Reserva una llamada gratuita",
    "planner_title": "🌱 Tu Planificador del Futuro",
    "personal_info": "👤 Información Personal y Estilo de Vida",
    "living_expenses": "🏠 Gastos de Vida",
    "life_goals": "🧭 Objetivos de Vida y Planes Futuros",
    "investment_preferences": "🎯 Objetivos y Preferencias de Inversión",
    "projection_overview": "📊 Vista General de la Proyección Financiera",
    "summary": "📝 Resumen y Recomendaciones",
    "suggestions": "✅ Sugerencias",
    "about_me_text": """
        Mi nombre es Alex y me apasiona ayudar a las personas a navegar con confianza por el panorama financiero suizo. Ya seas un residente o un recién llegado a Suiza, simplifico temas complejos como la planificación para la jubilación, el seguro de salud, los impuestos y la gestión diaria del presupuesto.

        Con años de experiencia ayudando a expatriados y ciudadanos suizos, ofrezco asesoramiento personalizado que funciona en la vida real, no solo en el papel.
    """,
    "what_i_help_text": """
        - Comprender y optimizar tu 3er pilar (Säule 3a)
        - Comparar modelos de Krankenkasse y ahorrar en el seguro de salud
        - Presupuestar de manera efectiva en ciudades de alto costo
        - Declarar impuestos y maximizar las deducciones
        - Planificación financiera para familias, freelancers y expatriados
        - Introducción a la inversión en ETFs en Suiza
    """,
    "topic_1_title": "3er Pilar Explicado (Säule 3a)",
    "topic_1_summary": "Descubre cómo reducir tus impuestos mientras ahorras para la jubilación. Aprende la diferencia entre las opciones bancarias y de seguros, y por qué no todas las cuentas 3a son iguales.",
    "topic_1_chart_caption": "Crecimiento con ventajas fiscales a lo largo del tiempo",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "Cómo Funciona Realmente Krankenkasse",
    "topic_2_summary": "¿Confundido con el seguro de salud suizo? Explicamos la cobertura básica y suplementaria, modelos como Telmed y HMO, y cómo ahorrar más de 1,000 CHF al año.",
    "topic_2_chart_caption": "Posibles ahorros anuales con comparación de modelos",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Invertir en Suiza 101",
    "topic_3_summary": "Aprende cómo empezar a invertir con solo 100 CHF al mes. Compararemos ETFs vs ahorros, explicaremos los niveles de riesgo y te mostraremos cómo abrir tu primera cuenta de corretaje en Suiza.",
    "topic_3_chart_caption": "Comparación de crecimiento: ETF vs Ahorros",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Deducciones Fiscales que Probablemente Estás Perdiendo",
    "topic_4_summary": "Desde las contribuciones al 3a hasta los gastos de viaje, hacemos que tu declaración de impuestos trabaje a tu favor. Estos consejos pueden devolverte cientos de francos.",
    "topic_4_chart_caption": "Gráfico de posibles ahorros fiscales",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Presupuesto Mensual en Suiza",
    "topic_5_summary": "Vivir en Suiza es caro, pero hacer presupuesto no tiene por qué ser difícil. Aquí tienes una forma sencilla de estructurar tus ingresos mensuales utilizando la regla 50/30/20 adaptada a los costos suizos.",
    "topic_5_chart_caption": "Ejemplo de asignación del presupuesto",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "El Costo Real de Vivir Solo en Suiza",
    "topic_6_summary": "¿Estás pensando en mudarte solo? Desglosamos el alquiler, el seguro, el transporte y la comida para que puedas planificar de manera realista vivir solo en Zurich, Ginebra o incluso Lugano.",
    "topic_6_chart_caption": "Desglose estimado de los costos para vivir solo",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Fecha Límite para Cambiar Krankenkasse: Lo que Necesitas Saber",
    "topic_7_summary": "Cada noviembre tienes la oportunidad de ahorrar. Este artículo explica la fecha límite, cómo comparar las primas y cómo enviar una carta de cancelación.",
    "topic_7_chart_caption": "Ahorros por cambios de plan a tiempo",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "Pilar 3a: ¿Banco o Seguro?",
    "topic_8_summary": "¿Indeciso? Descubre por qué uno ofrece más flexibilidad, mientras que el otro puede comprometerte por décadas. Alex te ayuda a decidir cuál se ajusta mejor a tus objetivos.",
    "topic_8_chart_caption": "Comparación de flexibilidad y rendimiento",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Estabilidad del Franco Suizo y la Inversión",
    "topic_9_summary": "¿Por qué se considera seguro el CHF? ¿Qué significa eso para tu estrategia de inversión a largo plazo? Entiende la fortaleza de la moneda en términos simples.",
    "topic_9_chart_caption": "Comparación del CHF con otras monedas globales",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Expatriados: Cómo Navegar las Finanzas Suizas",
    "topic_10_summary": "¿Nuevo en Suiza? Aquí tienes una guía rápida sobre el seguro de salud, la cobertura obligatoria y cómo empezar a ahorrar o invertir incluso siendo un recién llegado.",
    "topic_10_chart_caption": "Hoja de ruta de integración financiera para nuevos residentes",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
      "personal_info_expander": "👤 Información personal y estilo de vida",
      "age": "🎂 Edad",
      "relationship_status": "💍 Estado civil",
      "relationship_status_options": ["Soltero", "Casado", "Divorciado", "Viudo"],
      "has_kids": "👶 ¿Tienes hijos?",
      "has_kids_options": ["No", "Sí", "Planeo tener"],
      "pets": "🐶 Mascotas",
      "pets_options": ["Perro", "Gato", "Ninguno", "Otro"],
      "hobbies": "🎨 Pasatiempos",
      "hobbies_options": ["Viajar", "Deportes", "Leer", "Jugar", "Arte", "Otro"],
      "wants_to_travel": "✈️ Frecuencia de viajes",
      "wants_to_travel_options": ["Sí", "No", "A veces"],
      "career_field": "💼 Sector laboral",
      "career_field_options": ["Tecnología", "Finanzas", "Salud", "Educación", "Otro"],
      "current_salary": "💵 Ingreso mensual actual (CHF)",
      "expenses_expander": "🏠 Gastos de vida",
      "rent": "🏡 Alquiler / Hipoteca mensual",
      "food": "🍽️ Comida y compras",
      "transport": "🚗 Transporte",
      "entertainment": "🎭 Entretenimiento y pasatiempos",
      "healthcare": "🩺 Asistencia sanitaria y seguro",
      "misc": "🧾 Otros gastos",
      "total_expenses_label": "💸 Costo total mensual de vida",
      "preferences_note": "💭 _Estas preferencias ayudan a personalizar tu hoja de ruta financiera más a fondo._",
      "goals_expander": "🧭 Objetivos de vida y planes futuros",
      "wants_children": "👶 ¿Planeas tener (más) hijos?",
      "wants_children_options": ["No", "Sí", "Tal vez"],
      "dream_trip": "✈️ Destino o viaje soñado",
      "travel_budget": "💸 Presupuesto anual de viajes (CHF)",
      "major_purchase": "🚗 ¿Próxima gran compra?",
      "major_purchase_options": ["Casa", "Coche", "Educación", "Startup", "Ninguno"],
      "career_goal": "💼 Ambiciones profesionales o cambios de trabajo en los próximos 5–10 años?",
      "lifestyle_upgrades": "🌟 Mejoras deseadas en tu estilo de vida",
      "lifestyle_upgrades_options": ["Vivir en lujo", "Flexibilidad laboral", "Más tiempo libre", "Mudarse al extranjero", "Ninguno"],
      "wellness_goals": "🧘‍♀️ Objetivos relacionados con el bienestar o la salud mental",
      "wellness_goals_options": ["Sí", "No", "Tratando de priorizar"],
      "investment_expander": "🎯 Objetivos y preferencias de inversión",
      "wants_to_buy_house": "🏠 ¿Planeas comprar una casa?",
      "wants_to_buy_house_options": ["Sí", "No", "Tal vez"],
      "retirement_age": "🎉 Edad deseada para la jubilación",
      "owns_home": "🏘️ ¿Tienes casa propia?",
      "owns_home_options": ["Sí", "No"],
      "has_3a": "💼 ¿Tienes un 3er Pilar?",
      "has_3a_options": ["Sí", "No"],
      "has_etfs": "📈 ¿Invertir en ETFs/Fondos Indexados?",
      "has_etfs_options": ["Sí", "No"],
      "other_assets": "💰 Otros activos",
      "other_assets_options": ["Bienes raíces", "Cripto", "Negocios", "Ahorros de alto rendimiento", "Ninguno"],
      "wants_to_invest_more": "➕ ¿Quieres invertir más?",
      "wants_to_invest_more_options": ["Sí", "No", "Tal vez"],
      "initial_savings": "💰 Ahorros e inversiones actuales (CHF)"
    },
    "projection_overview": "📊 Vista general de la proyección financiera",
    "income_vs_expenses_chart": "💵 Ingreso vs Gastos",
    "summary_recommendations": "📝 Resumen y recomendaciones",
    "suggestions": "✅ Sugerencias"

},


    
    "Catalan": {
    "title": "🇨🇭 Finances Suïsses Fàcils",
    "subtitle": "Hola, sóc Alex. T'ajudo a entendre les inversions, l'assegurança de salut i els impostos a Suïssa.",
    "about_me": "👋 Sobre mi",
    "what_i_help": "Com t'ajudo",
    "topics": "📘 Temes Financers",
    "resources": "📂 Eines & Guies gratuïtes",
    "user": "📈 Projecció financera personal",
    "book_call": "📅 Reserva una trucada gratuïta",
    "planner_title": "🌱 El teu planificador del futur",
    "personal_info": "👤 Informació personal & estil de vida",
    "living_expenses": "🏠 Despeses de vida",
    "life_goals": "🧭 Objectius de vida & plans",
    "investment_preferences": "🎯 Objectius & preferències d'inversió",
    "projection_overview": "📊 Visió general de la projecció financera",
    "summary": "📝 Resum & Recomanacions",
    "suggestions": "✅ Suggeriments",
    "about_me_text": """
        El meu nom és Alex, i m'apassiona ajudar les persones a navegar amb confiança pel paisatge financer suís. Tant si ets un local com si ets nou a Suïssa, simplifico temes complexos com la planificació de la jubilació, l'assegurança de salut, l'estalvi d'impostos i el pressupost diari.

        Amb anys d'experiència treballant amb expatriats i ciutadans suïssos, ofereixo consells personalitzats que funcionen a la vida real, no només sobre el paper.
    """,
    "what_i_help_text": """
        - Entendre i optimitzar el teu 3r Pilar suís (Säule 3a)
        - Comparar models de Krankenkasse i estalviar en assegurança de salut
        - Pressupostar eficaçment en ciutats de cost elevat
        - Presentar impostos i maximitzar deduccions
        - Planificació financera per a famílies, treballadors autònoms i expatriats
        - Introducció a la inversió en ETFs a Suïssa
    """,
    "topic_1_title": "Pilar 3a explicat (Säule 3a)",
    "topic_1_summary": "Descobreix com reduir els teus impostos mentre estalvies per la jubilació. Aprèn la diferència entre les opcions bancàries i d'assegurança, i per què no tots els comptes 3a són iguals.",
    "topic_1_chart_caption": "Creixement amb avantatges fiscals al llarg del temps",
    "topic_1_link": "https://www.ch.ch/en/retirement/third-pillar/",
    "topic_2_title": "Com funciona realment el Krankenkasse",
    "topic_2_summary": "Estàs confós amb l'assegurança de salut suïssa? T'explico les cobertures bàsiques i addicionals, els models com Telmed i HMO, i com estalviar més de 1.000 CHF a l'any.",
    "topic_2_chart_caption": "Estalvi potencial anual amb comparativa de models",
    "topic_2_link": "https://www.ch.ch/en/health/health-insurance/",
    "topic_3_title": "Inversió a Suïssa 101",
    "topic_3_summary": "Aprèn a començar a invertir amb només 100 CHF/mes. Compararem ETFs vs. estalvis, explicarem els nivells de risc i t'ensenyarem a obrir el teu primer compte de corretatge suís.",
    "topic_3_chart_caption": "Comparativa de creixement: ETF vs. Estalvis",
    "topic_3_link": "https://www.finanztipp.ch/etf/",
    "topic_4_title": "Deduccions fiscals que probablement estàs perdent",
    "topic_4_summary": "Des de les contribucions al 3a fins a les despeses de viatge, fem que la teva declaració d'impostos treballi per a tu. Aquests consells poden suposar centenars de francs més al teu butxaca.",
    "topic_4_chart_caption": "Gràfic d'estalvi fiscal possible",
    "topic_4_link": "https://www.ch.ch/en/taxes/deductions/",
    "topic_5_title": "Pressupost mensual a Suïssa",
    "topic_5_summary": "Vivir a Suïssa és car, però no és difícil fer un pressupost. Aquí tens una manera senzilla d'estructurar els teus ingressos mensuals utilitzant la regla 50/30/20 adaptada als costos suïssos.",
    "topic_5_chart_caption": "Exemple d'assignació de pressupost",
    "topic_5_link": "https://www.ch.ch/en/money-budget/",
    "topic_6_title": "El cost real de viure sol a Suïssa",
    "topic_6_summary": "Penses en mudar-te? T'explico el lloguer, l'assegurança, el transport i el menjar per tal que puguis planificar realment per viure sol a Zuric, Ginebra o fins i tot Lugano.",
    "topic_6_chart_caption": "Desglossament estimat dels costos per viure sol",
    "topic_6_link": "https://www.ch.ch/en/living/",
    "topic_7_title": "Data límit de canvi de Krankenkasse: el que necessites saber",
    "topic_7_summary": "Cada novembre tens l'oportunitat d'estalviar. Aquest post t'explica la data límit, com comparar primes i enviar una carta de cancel·lació.",
    "topic_7_chart_caption": "Estalvi d'un canvi de pla a temps",
    "topic_7_link": "https://www.ch.ch/en/health/health-insurance/change-insurance/",
    "topic_8_title": "Pilar 3a: Banc o assegurança?",
    "topic_8_summary": "Penses en les teves opcions? T'ensenyem per què un ofereix més flexibilitat, mentre que l'altre et pot bloquejar durant dècades. T'ajudem a decidir quina opció s'adapta millor als teus objectius.",
    "topic_8_chart_caption": "Comparació de flexibilitat i rendiment",
    "topic_8_link": "https://www.moneyland.ch/en/3a-pillar-bank-or-insurance",
    "topic_9_title": "Estabilitat del franc suís i inversió",
    "topic_9_summary": "Per què el CHF és considerat 'segur'? Què significa això per a la teva estratègia d'inversió a llarg termini? Entén la força de la moneda en termes senzills.",
    "topic_9_chart_caption": "Comparativa del CHF amb altres monedes globals",
    "topic_9_link": "https://www.snb.ch/en/",
    "topic_10_title": "Expatriats: Com navegar per les finances suïsses",
    "topic_10_summary": "Són nous a Suïssa? Aquí tens una guia ràpida sobre l'assegurança de salut, la cobertura obligatòria i com començar a estalviar o invertir fins i tot com a nouvingut.",
    "topic_10_chart_caption": "Full de ruta d'integració financera per als nous residents",
    "topic_10_link": "https://www.ch.ch/en/moving-to-switzerland/",
    "planner_inputs": {
      "personal_info_expander": "👤 Informació personal & estil de vida",
      "age": "🎂 Edat",
      "relationship_status": "💍 Estat civil",
      "relationship_status_options": ["Solter/a", "Casat/ada", "Divorciat/ada", "Víudo/a"],
      "has_kids": "👶 Tens fills?",
      "has_kids_options": ["No", "Sí", "Tinc pensat tenir fills"],
      "pets": "🐶 Mascotes",
      "pets_options": ["Gos", "Gat", "Cap", "Altres"],
      "hobbies": "🎨 Passatemps",
      "hobbies_options": ["Viatges", "Esports", "Lectura", "Jocs", "Art", "Altres"],
      "wants_to_travel": "✈️ Freqüència de viatges",
      "wants_to_travel_options": ["Sí", "No", "De vegades"],
      "career_field": "💼 Sector professional",
      "career_field_options": ["Tecnologia", "Finances", "Salut", "Educació", "Altres"],
      "current_salary": "💵 Sou mensual actual (CHF)",

      "expenses_expander": "🏠 Despeses de vida",
      "rent": "🏡 Lloguer / Hipoteca mensual",
      "food": "🍽️ Menjar & Supermercat",
      "transport": "🚗 Transport",
      "entertainment": "🎭 Entreteniment & Passatemps",
      "healthcare": "🩺 Salut & Assegurança",
      "misc": "🧾 Altres despeses",
      "total_expenses_label": "💸 Cost total mensual de despeses",
      "preferences_note": "💭 _Aquestes preferències ajuden a personalitzar més profundament el teu pla financer._",

      "goals_expander": "🧭 Objectius de vida & plans futurs",
      "wants_children": "👶 Tens pensat tenir (més) fills?",
      "wants_children_options": ["No", "Sí", "Potser"],
      "dream_trip": "✈️ Destí o viatge somiat",
      "travel_budget": "💸 Pressupost anual per a viatges (CHF)",
      "major_purchase": "🚗 Quina serà la teva pròxima gran compra?",
      "major_purchase_options": ["Casa", "Cotxe", "Educació", "Startup", "Cap"],
      "career_goal": "💼 Objectius professionals o canvis laborals en els pròxims 5-10 anys",
      "lifestyle_upgrades": "🌟 Millores desitjades en l'estil de vida",
      "lifestyle_upgrades_options": ["Vida de luxe", "Flexibilitat laboral", "Més temps lliure", "Mudar-se a l'estranger", "Cap"],
      "wellness_goals": "🧘‍♀️ Objectius de benestar o salut mental",
      "wellness_goals_options": ["Sí", "No", "Estic intentant prioritzar"],

      "investment_expander": "🎯 Objectius & preferències d'inversió",
      "wants_to_buy_house": "🏠 Tens pensat comprar una casa?",
      "wants_to_buy_house_options": ["Sí", "No", "Potser"],
      "retirement_age": "🎉 Edat desitjada per a la jubilació",
      "owns_home": "🏘️ Tens una casa pròpia?",
      "owns_home_options": ["Sí", "No"],
      "has_3a": "💼 Tens un 3r Pilar?",
      "has_3a_options": ["Sí", "No"],
      "has_etfs": "📈 Inverteixes en ETFs/Fons indexats?",
      "has_etfs_options": ["Sí", "No"],
      "other_assets": "💰 Altres actius",
      "other_assets_options": ["Immobiliari", "Criptomonedes", "Negoci", "Estalvis de rendiment alt", "Cap"],
      "wants_to_invest_more": "➕ Vols invertir més?",
      "wants_to_invest_more_options": ["Sí", "No", "Potser"],
      "initial_savings": "💰 Estalvis & inversions actuals (CHF)"
    },
    "projection_overview": "📊 Visió general de la projecció financera",
    "income_vs_expenses_chart": "💵 Ingressos vs Despeses",
    "summary_recommendations": "📝 Resum & Recomanacions",
    "suggestions": "✅ Suggeriments"
  }

}
