# idiomes.py

translations = {
    "English": {
        "title": "🇨🇭 Swiss Finance Made Simple",
        "subtitle": "Hi, I'm Alex. I help you understand investments, Krankenkasse & taxes in Switzerland.",
        "about_me": "👋 About Me",
        "what_i_help": "What I Can Help With",
        "topics": "📘 Financial Topics",
        "resources": "📂 Free Tools & Guides",
        "user": "📈 Personal Finance Projection",
        "book_call": "📅 Book a free call",
        "planner_title": "🌱 Your Future Planner",
        "personal_info": "👤 Personal & Lifestyle Information",
        "living_expenses": "🏠 Living Expenses",
        "life_goals": "🧭 Life Goals & Future Plans",
        "investment_preferences": "🎯 Goals & Investment Preferences",
        "projection_overview": "📊 Financial Projection Overview",
        "summary": "📝 Summary & Recommendations",
        "suggestions": "✅ Suggestions"
    },
    "Deutsch": {
        "title": "🇨🇭 Schweizer Finanzen einfach erklärt",
        "subtitle": "Hallo, ich bin Alex. Ich helfe dir, Investitionen, Krankenkasse und Steuern in der Schweiz zu verstehen.",
        "about_me": "👋 Über mich",
        "what_i_help": "Womit ich helfen kann",
        "topics": "📘 Finanzthemen",
        "resources": "📂 Kostenlose Tools & Leitfäden",
        "user": "📈 Persönliche Finanzprojektion",
        "book_call": "📅 Kostenloses Gespräch buchen",
        "planner_title": "🌱 Dein Zukunftsplaner",
        "personal_info": "👤 Persönliche Informationen",
        "living_expenses": "🏠 Lebenshaltungskosten",
        "life_goals": "🧭 Lebensziele & Zukunftspläne",
        "investment_preferences": "🎯 Ziele & Investitionspräferenzen",
        "projection_overview": "📊 Finanzielle Projektion",
        "summary": "📝 Zusammenfassung & Empfehlungen",
        "suggestions": "✅ Vorschläge"
    },
    "Français": {
        "title": "🇨🇭 La finance suisse simplifiée",
        "subtitle": "Salut, je suis Alex. Je t'aide à comprendre les investissements, l'assurance maladie et les impôts en Suisse.",
        "about_me": "👋 À propos de moi",
        "what_i_help": "Ce que je peux vous aider à comprendre",
        "topics": "📘 Sujets financiers",
        "resources": "📂 Outils et guides gratuits",
        "user": "📈 Projection des finances personnelles",
        "book_call": "📅 Réserver un appel gratuit",
        "planner_title": "🌱 Planificateur de votre avenir",
        "personal_info": "👤 Informations personnelles",
        "living_expenses": "🏠 Dépenses de vie",
        "life_goals": "🧭 Objectifs et projets de vie",
        "investment_preferences": "🎯 Objectifs et préférences d’investissement",
        "projection_overview": "📊 Aperçu de la projection financière",
        "summary": "📝 Résumé & Recommandations",
        "suggestions": "✅ Suggestions"
    },
    "Italiano": {
        "title": "🇨🇭 Finanza Svizzera Semplificata",
        "subtitle": "Ciao, sono Alex. Ti aiuto a capire investimenti, cassa malati e tasse in Svizzera.",
        "about_me": "👋 Chi sono",
        "what_i_help": "Come posso aiutarti",
        "topics": "📘 Argomenti finanziari",
        "resources": "📂 Strumenti e guide gratuite",
        "user": "📈 Proiezione Finanziaria Personale",
        "book_call": "📅 Prenota una chiamata gratuita",
        "planner_title": "🌱 Il tuo piano futuro",
        "personal_info": "👤 Informazioni personali",
        "living_expenses": "🏠 Spese di vita",
        "life_goals": "🧭 Obiettivi di vita e futuri",
        "investment_preferences": "🎯 Obiettivi e preferenze di investimento",
        "projection_overview": "📊 Proiezione Finanziaria",
        "summary": "📝 Riepilogo & Raccomandazioni",
        "suggestions": "✅ Suggerimenti"
    },
    "Español": {
        "title": "🇨🇭 Finanzas suizas simplificadas",
        "subtitle": "Hola, soy Alex. Te ayudo a entender inversiones, Krankenkasse y impuestos en Suiza.",
        "about_me": "👋 Sobre mí",
        "what_i_help": "En qué puedo ayudarte",
        "topics": "📘 Temas financieros",
        "resources": "📂 Herramientas y guías gratuitas",
        "user": "📈 Proyección Financiera Personal",
        "book_call": "📅 Reserva una llamada gratuita",
        "planner_title": "🌱 Tu Planificador de Futuro",
        "personal_info": "👤 Información personal y estilo de vida",
        "living_expenses": "🏠 Gastos de vida",
        "life_goals": "🧭 Metas de vida y planes futuros",
        "investment_preferences": "🎯 Objetivos y preferencias de inversión",
        "projection_overview": "📊 Vista de la proyección financiera",
        "summary": "📝 Resumen y Recomendaciones",
        "suggestions": "✅ Sugerencias"
    },
    "Català": {
        "title": "🇨🇭 Finances suïsses fetes fàcils",
        "subtitle": "Hola, soc l'Alex. T'ajudo a entendre les inversions, la seguretat mèdica i els impostos a Suïssa.",
        "about_me": "👋 Sobre mi",
        "what_i_help": "En què et puc ajudar",
        "topics": "📘 Temes financers",
        "resources": "📂 Eines i guies gratuïtes",
        "user": "📈 Projecció financera personal",
        "book_call": "📅 Reserva una trucada gratuïta",
        "planner_title": "🌱 El teu planificador de futur",
        "personal_info": "👤 Informació personal i estil de vida",
        "living_expenses": "🏠 Despeses de vida",
        "life_goals": "🧭 Objectius i plans de futur",
        "investment_preferences": "🎯 Objectius i preferències d'inversió",
        "projection_overview": "📊 Resum de la projecció financera",
        "summary": "📝 Resum i recomanacions",
        "suggestions": "✅ Suggeriments"
    }
}
